export const MAGNA_RECOVERY_V3_SCHEMA = 3n;
export const MAGNA_PASSPORT_CREDENTIAL_TYPE = 1n;

// Intentionally identical to rooted A2 issuance. The V3 authorization is
// domain-separated below; identity lookup must match the note already issued.
export const MAGNA_GHOST_DS = 0x4d414748; // "MAGH"
export const MAGNA_ROOT_DS = 0x4d414749; // "MAGI"
export const MAGNA_RECOVERY_INTENT_V3_DS = 0x4d524933; // "MRI3"
export const MAGNA_RECOVERY_AUTH_V3_DS = 0x4d524133; // "MRA3"
export const MAGNA_RECOVERY_BLIND_V3_DS = 0x4d524233; // "MRB3"
export const MAGNA_RECOVERY_TRUST_V3_DS = 0x4d525433; // "MRT3"

// Existing passport-v2 commitment domains. V3 deliberately composes these
// formulas instead of introducing a second credential schema.
export const MAGNA_CLAIMS_DS = 0x4d414743; // "MAGC"
export const MAGNA_PASSPORT_NATIONALITY_COMMITMENT_DS = 0x4d414e43; // "MANC"
export const MAGNA_PASSPORT_EXPIRY_COMMITMENT_DS = 0x4d414558; // "MAEX"
export const MAGNA_PASSPORT_COMMITTED_CLAIMS_SCHEMA = 2n;

export const MAGNA_RECOVERY_BIND_PREFIX = "magna-recovery-v3:";
export const MAGNA_RECOVERY_PROOF_MAX_AGE_SECONDS = 60n * 60n;
export const MAGNA_RECOVERED_CREDENTIAL_MAX_AGE_SECONDS = 30n * 24n * 60n * 60n;
export const MAGNA_RECOVERY_WRAPPER_PUBLIC_INPUT_COUNT = 7;

export const ZKPASSPORT_OUTER_NAME = "outer_count_7";
export const ZKPASSPORT_OUTER_VERSION = "0.20.0";
export const ZKPASSPORT_OUTER_PUBLIC_INPUT_COUNT = 12;
export const ZKPASSPORT_OUTER_VKEY_HASH =
  0x19d93a8a69386b80903a8559d884bea729dc1ecc1db48afc6d3bb73d4ed3abben;
export const ZKPASSPORT_OPRF_KEY_ID = "1";
export const ZKPASSPORT_OPRF_PUBLIC_KEY_HASH =
  1178201404428554206520802247552222388413553631367032661928167491793274360628n;
export const ZKPASSPORT_NULLIFIER_TYPE_SALTED = 1n;
export const ZKPASSPORT_NULLIFIER_TYPE_NON_SALTED_MOCK = 2n;
export const ZKPASSPORT_DEVELOPMENT_OPRF_PUBLIC_KEY_HASH = 0n;

export const ZKPASSPORT_OUTER_CERTIFICATE_ROOT_INDEX = 0;
export const ZKPASSPORT_OUTER_CIRCUIT_ROOT_INDEX = 1;
export const ZKPASSPORT_OUTER_CURRENT_DATE_INDEX = 2;
export const ZKPASSPORT_OUTER_SERVICE_SCOPE_INDEX = 3;
export const ZKPASSPORT_OUTER_SERVICE_SUBSCOPE_INDEX = 4;
export const ZKPASSPORT_OUTER_NULLIFIER_TYPE_INDEX = 9;
export const ZKPASSPORT_OUTER_IDENTITY_VALUE_INDEX = 10;
export const ZKPASSPORT_OUTER_OPRF_PUBLIC_KEY_HASH_INDEX = 11;

export const RECOVERY_WRAPPER_SCHEMA_INDEX = 0;
export const RECOVERY_WRAPPER_AUTHORIZATION_INDEX = 1;
export const RECOVERY_WRAPPER_SECRET_HASH_INDEX = 2;
export const RECOVERY_WRAPPER_CURRENT_DATE_INDEX = 3;
export const RECOVERY_WRAPPER_CERTIFICATE_ROOT_INDEX = 4;
export const RECOVERY_WRAPPER_CIRCUIT_ROOT_INDEX = 5;
export const RECOVERY_WRAPPER_TRUST_CONTEXT_INDEX = 6;
