[package]
name = "magna_instagram_proof"
type = "bin"
authors = ["Magna Team"]
compiler_version = ">=1.0.0"

[dependencies]
zkemail = { tag = "v0.4.2", git = "https://github.com/zkemail/zkemail.nr", directory = "lib" }
