
/* Autogenerated file, do not edit! */

/* eslint-disable */
import { AztecAddress, CompleteAddress } from '@aztec/aztec.js/addresses';
import { type AbiType, type AztecAddressLike, type ContractArtifact, EventSelector, decodeFromAbi, type EthAddressLike, type FieldLike, type FunctionSelectorLike, loadContractArtifact, loadContractArtifactForPublic, type NoirCompiledContract, type OptionLike, type U128Like, type WrappedFieldLike } from '@aztec/aztec.js/abi';
import { Contract, ContractBase, ContractFunctionInteraction, type ContractMethod, type ContractStorageLayout, type DeployInstantiationOptions, DeployMethod } from '@aztec/aztec.js/contracts';
import { EthAddress } from '@aztec/aztec.js/addresses';
import { Fr, Point } from '@aztec/aztec.js/fields';
import { type PublicKey, PublicKeys } from '@aztec/aztec.js/keys';
import type { Wallet } from '@aztec/aztec.js/wallet';
import MagnaIssuerContractArtifactJson from '../../../contracts/magna-issuer/target/magna_issuer-MagnaIssuer.json' with { type: 'json' };
export const MagnaIssuerContractArtifact = loadContractArtifact(MagnaIssuerContractArtifactJson as NoirCompiledContract);



/**
 * Type-safe interface for contract MagnaIssuer;
 */
export class MagnaIssuerContract extends ContractBase {
  
  private constructor(
    address: AztecAddress,
    wallet: Wallet,
  ) {
    super(address, MagnaIssuerContractArtifact, wallet);
  }
  

  
  /**
   * Creates a contract instance.
   * @param address - The deployed contract's address.
   * @param wallet - The wallet to use when interacting with the contract.
   * @returns A new Contract instance.
   */
  public static at(
    address: AztecAddress,
    wallet: Wallet,
  ): MagnaIssuerContract {
    return Contract.at(address, MagnaIssuerContract.artifact, wallet) as MagnaIssuerContract;
  }

  
  /**
   * Creates a tx to deploy a new instance of this contract.
   * @param instantiation - Optional address-affecting parameters (salt, deployer / universalDeploy, publicKeys).
   *                       Salt defaults to a random value; the deployer is locked lazily from the first send-time `from`.
   */
  public static deploy(wallet: Wallet, orchestrator_address: AztecAddressLike, verify_meter_hook_address: AztecAddressLike, instantiation?: DeployInstantiationOptions) {
    return DeployMethod.create<MagnaIssuerContract>(
      wallet,
      {
        artifact: MagnaIssuerContractArtifact,
        postDeployCtor: (instance, wallet) => MagnaIssuerContract.at(instance.address, wallet),
        args: [orchestrator_address, verify_meter_hook_address],
      },
      instantiation,
    );
  }

  /**
   * Creates a tx to deploy a new instance of this contract using the specified constructor method.
   */
  public static deployWithOpts<M extends keyof MagnaIssuerContract['methods']>(
    opts: { method?: M; wallet: Wallet; instantiation?: DeployInstantiationOptions },
    ...args: Parameters<MagnaIssuerContract['methods'][M]>
  ) {
    return DeployMethod.create<MagnaIssuerContract>(
      opts.wallet,
      {
        artifact: MagnaIssuerContractArtifact,
        postDeployCtor: (instance, wallet) => MagnaIssuerContract.at(instance.address, wallet),
        args,
        constructorNameOrArtifact: opts.method ?? 'constructor',
      },
      opts.instantiation,
    );
  }
  

  
  /**
   * Returns this contract's artifact.
   */
  public static get artifact(): ContractArtifact {
    return MagnaIssuerContractArtifact;
  }

  /**
   * Returns this contract's artifact with public bytecode.
   */
  public static get artifactForPublic(): ContractArtifact {
    return loadContractArtifactForPublic(MagnaIssuerContractArtifactJson as NoirCompiledContract);
  }
  

  public static get storage(): ContractStorageLayout<'orchestrator' | 'verify_meter_hook' | 'company_sponsor_gateways' | 'disabled_company_sponsor_gateways' | 'consumer_gateways' | 'disabled_consumer_gateways' | 'sponsored_credential_type_mask' | 'verify_meter_count' | 'credential_notes' | 'status_notes' | 'recovery_notes' | 'root_status_notes' | 'root_recovery_notes' | 'root_authority_notes' | 'linked_credential_notes' | 'linked_status_notes' | 'linked_recovery_notes'> {
      return {
        orchestrator: {
      slot: new Fr(1n),
    },
verify_meter_hook: {
      slot: new Fr(3n),
    },
company_sponsor_gateways: {
      slot: new Fr(5n),
    },
disabled_company_sponsor_gateways: {
      slot: new Fr(6n),
    },
consumer_gateways: {
      slot: new Fr(7n),
    },
disabled_consumer_gateways: {
      slot: new Fr(8n),
    },
sponsored_credential_type_mask: {
      slot: new Fr(9n),
    },
verify_meter_count: {
      slot: new Fr(13n),
    },
credential_notes: {
      slot: new Fr(14n),
    },
status_notes: {
      slot: new Fr(15n),
    },
recovery_notes: {
      slot: new Fr(16n),
    },
root_status_notes: {
      slot: new Fr(17n),
    },
root_recovery_notes: {
      slot: new Fr(18n),
    },
root_authority_notes: {
      slot: new Fr(19n),
    },
linked_credential_notes: {
      slot: new Fr(20n),
    },
linked_status_notes: {
      slot: new Fr(21n),
    },
linked_recovery_notes: {
      slot: new Fr(22n),
    }
      } as ContractStorageLayout<'orchestrator' | 'verify_meter_hook' | 'company_sponsor_gateways' | 'disabled_company_sponsor_gateways' | 'consumer_gateways' | 'disabled_consumer_gateways' | 'sponsored_credential_type_mask' | 'verify_meter_count' | 'credential_notes' | 'status_notes' | 'recovery_notes' | 'root_status_notes' | 'root_recovery_notes' | 'root_authority_notes' | 'linked_credential_notes' | 'linked_status_notes' | 'linked_recovery_notes'>;
    }
    

  /** Type-safe wrappers for the public methods exposed by the contract. */
  public declare methods: {
    
    /** add_company_sponsor_gateway(gateway: struct) */
    add_company_sponsor_gateway: ((gateway: AztecAddressLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** add_consumer_gateway(gateway: struct) */
    add_consumer_gateway: ((gateway: AztecAddressLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** constructor(orchestrator_address: struct, verify_meter_hook_address: struct) */
    constructor: ((orchestrator_address: AztecAddressLike, verify_meter_hook_address: AztecAddressLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_credential_hinted(owner: struct, claims_hash: field) */
    get_credential_hinted: ((owner: AztecAddressLike, claims_hash: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_linked_credential_hinted(owner: struct, root_commitment: field, claims_hash: field) */
    get_linked_credential_hinted: ((owner: AztecAddressLike, root_commitment: FieldLike, claims_hash: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_linked_recovery_hinted(owner: struct, root_commitment: field, claims_hash: field) */
    get_linked_recovery_hinted: ((owner: AztecAddressLike, root_commitment: FieldLike, claims_hash: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_linked_status_hinted(owner: struct, root_commitment: field, claims_hash: field) */
    get_linked_status_hinted: ((owner: AztecAddressLike, root_commitment: FieldLike, claims_hash: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_recovery_hinted(owner: struct, claims_hash: field) */
    get_recovery_hinted: ((owner: AztecAddressLike, claims_hash: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_root_authority_hinted(owner: struct, root_commitment: field, claims_hash: field) */
    get_root_authority_hinted: ((owner: AztecAddressLike, root_commitment: FieldLike, claims_hash: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_root_recovery_hinted(owner: struct, root_commitment: field) */
    get_root_recovery_hinted: ((owner: AztecAddressLike, root_commitment: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_root_status_hinted(owner: struct, root_commitment: field) */
    get_root_status_hinted: ((owner: AztecAddressLike, root_commitment: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_sponsored_credential_type_mask() */
    get_sponsored_credential_type_mask: (() => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_status_hinted(owner: struct, claims_hash: field) */
    get_status_hinted: ((owner: AztecAddressLike, claims_hash: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_verify_meter_count() */
    get_verify_meter_count: (() => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** is_company_sponsor_gateway(gateway: struct) */
    is_company_sponsor_gateway: ((gateway: AztecAddressLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** is_consumer_gateway(gateway: struct) */
    is_consumer_gateway: ((gateway: AztecAddressLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** offchain_receive(messages: struct) */
    offchain_receive: ((messages: { ciphertext: FieldLike[], recipient: AztecAddressLike, tx_hash: OptionLike<FieldLike>, anchor_block_timestamp: (bigint | number) }[]) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** public_dispatch(selector: field) */
    public_dispatch: ((selector: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** recover(hinted_recovery: struct, new_active_owner: struct, remint_credential: boolean) */
    recover: ((hinted_recovery: { note: { revocation_secret: FieldLike, claims_hash: FieldLike, credential_type: (bigint | number), expiry_ts: (bigint | number) }, contract_address: AztecAddressLike, owner: AztecAddressLike, randomness: FieldLike, storage_slot: FieldLike, metadata: { stage: (bigint | number), maybe_note_nonce: FieldLike } }, new_active_owner: AztecAddressLike, remint_credential: boolean) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** recover_root(hinted_root_recovery: struct, new_active_owner: struct) */
    recover_root: ((hinted_root_recovery: { note: { root_commitment: FieldLike, revocation_secret: FieldLike }, contract_address: AztecAddressLike, owner: AztecAddressLike, randomness: FieldLike, storage_slot: FieldLike, metadata: { stage: (bigint | number), maybe_note_nonce: FieldLike } }, new_active_owner: AztecAddressLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** refresh_root_authority(ghost_owner: struct, hinted_root_status: struct, hinted_root_authority: struct, claims_hash: field, authority_expiry_ts: integer) */
    refresh_root_authority: ((ghost_owner: AztecAddressLike, hinted_root_status: { note: { root_commitment: FieldLike, revocation_secret: FieldLike }, contract_address: AztecAddressLike, owner: AztecAddressLike, randomness: FieldLike, storage_slot: FieldLike, metadata: { stage: (bigint | number), maybe_note_nonce: FieldLike } }, hinted_root_authority: { note: { root_commitment: FieldLike, claims_hash: FieldLike, authority_expiry_ts: (bigint | number), revocation_secret: FieldLike }, contract_address: AztecAddressLike, owner: AztecAddressLike, randomness: FieldLike, storage_slot: FieldLike, metadata: { stage: (bigint | number), maybe_note_nonce: FieldLike } }, claims_hash: FieldLike, authority_expiry_ts: (bigint | number)) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** register_credential(active_owner: struct, ghost_owner: struct, claims_hash: field, credential_type: integer, expiry_ts: integer) */
    register_credential: ((active_owner: AztecAddressLike, ghost_owner: AztecAddressLike, claims_hash: FieldLike, credential_type: (bigint | number), expiry_ts: (bigint | number)) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** register_credential_v2(active_owner: struct, ghost_owner: struct, claims_hash: field, credential_type: integer, credential_valid_until: integer) */
    register_credential_v2: ((active_owner: AztecAddressLike, ghost_owner: AztecAddressLike, claims_hash: FieldLike, credential_type: (bigint | number), credential_valid_until: (bigint | number)) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** register_linked_credential(active_owner: struct, ghost_owner: struct, root_commitment: field, claims_hash: field, credential_type: integer, expiry_ts: integer) */
    register_linked_credential: ((active_owner: AztecAddressLike, ghost_owner: AztecAddressLike, root_commitment: FieldLike, claims_hash: FieldLike, credential_type: (bigint | number), expiry_ts: (bigint | number)) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** register_root(active_owner: struct, ghost_owner: struct, root_commitment: field) */
    register_root: ((active_owner: AztecAddressLike, ghost_owner: AztecAddressLike, root_commitment: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** register_root_authority(active_owner: struct, root_commitment: field, claims_hash: field, authority_expiry_ts: integer) */
    register_root_authority: ((active_owner: AztecAddressLike, root_commitment: FieldLike, claims_hash: FieldLike, authority_expiry_ts: (bigint | number)) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** register_rooted_passport(active_owner: struct, ghost_owner: struct, root_commitment: field, claims_hash: field, expiry_ts: integer) */
    register_rooted_passport: ((active_owner: AztecAddressLike, ghost_owner: AztecAddressLike, root_commitment: FieldLike, claims_hash: FieldLike, expiry_ts: (bigint | number)) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** register_rooted_passport_v2(active_owner: struct, ghost_owner: struct, root_commitment: field, claims_hash: field, credential_valid_until: integer) */
    register_rooted_passport_v2: ((active_owner: AztecAddressLike, ghost_owner: AztecAddressLike, root_commitment: FieldLike, claims_hash: FieldLike, credential_valid_until: (bigint | number)) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** remove_company_sponsor_gateway(gateway: struct) */
    remove_company_sponsor_gateway: ((gateway: AztecAddressLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** remove_consumer_gateway(gateway: struct) */
    remove_consumer_gateway: ((gateway: AztecAddressLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** revoke_linked_credential(hinted_recovery: struct) */
    revoke_linked_credential: ((hinted_recovery: { note: { root_commitment: FieldLike, revocation_secret: FieldLike, claims_hash: FieldLike, credential_type: (bigint | number), expiry_ts: (bigint | number) }, contract_address: AztecAddressLike, owner: AztecAddressLike, randomness: FieldLike, storage_slot: FieldLike, metadata: { stage: (bigint | number), maybe_note_nonce: FieldLike } }) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** schedule_sponsored_credential_type_mask(new_mask: integer) */
    schedule_sponsored_credential_type_mask: ((new_mask: (bigint | number)) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** sync_state(scope: struct) */
    sync_state: ((scope: AztecAddressLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** verify(policy: struct, hinted_credential: struct, hinted_status: struct, min_age_proven: integer, nationality_alpha3_packed: field, sponsor_slot: integer) */
    verify: ((policy: { credential_type: (bigint | number), constraints: { claim_id: (bigint | number), op: (bigint | number), value: FieldLike }[] }, hinted_credential: { note: { claims_hash: FieldLike, credential_type: (bigint | number), expiry_ts: (bigint | number) }, contract_address: AztecAddressLike, owner: AztecAddressLike, randomness: FieldLike, storage_slot: FieldLike, metadata: { stage: (bigint | number), maybe_note_nonce: FieldLike } }, hinted_status: { note: { revocation_secret: FieldLike, claims_hash: FieldLike, credential_type: (bigint | number) }, contract_address: AztecAddressLike, owner: AztecAddressLike, randomness: FieldLike, storage_slot: FieldLike, metadata: { stage: (bigint | number), maybe_note_nonce: FieldLike } }, min_age_proven: (bigint | number), nationality_alpha3_packed: FieldLike, sponsor_slot: (bigint | number)) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** verify_consumer(caller: struct, policy: struct, hinted_credential: struct, hinted_status: struct, min_age_proven: integer, nationality_alpha3_packed: field, sponsor_slot: integer) */
    verify_consumer: ((caller: AztecAddressLike, policy: { credential_type: (bigint | number), constraints: { claim_id: (bigint | number), op: (bigint | number), value: FieldLike }[] }, hinted_credential: { note: { claims_hash: FieldLike, credential_type: (bigint | number), expiry_ts: (bigint | number) }, contract_address: AztecAddressLike, owner: AztecAddressLike, randomness: FieldLike, storage_slot: FieldLike, metadata: { stage: (bigint | number), maybe_note_nonce: FieldLike } }, hinted_status: { note: { revocation_secret: FieldLike, claims_hash: FieldLike, credential_type: (bigint | number) }, contract_address: AztecAddressLike, owner: AztecAddressLike, randomness: FieldLike, storage_slot: FieldLike, metadata: { stage: (bigint | number), maybe_note_nonce: FieldLike } }, min_age_proven: (bigint | number), nationality_alpha3_packed: FieldLike, sponsor_slot: (bigint | number)) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** verify_instagram(policy: struct, hinted_credential: struct, hinted_status: struct, handle_hash: field, sponsor_slot: integer) */
    verify_instagram: ((policy: { credential_type: (bigint | number), constraints: { claim_id: (bigint | number), op: (bigint | number), value: FieldLike }[] }, hinted_credential: { note: { claims_hash: FieldLike, credential_type: (bigint | number), expiry_ts: (bigint | number) }, contract_address: AztecAddressLike, owner: AztecAddressLike, randomness: FieldLike, storage_slot: FieldLike, metadata: { stage: (bigint | number), maybe_note_nonce: FieldLike } }, hinted_status: { note: { revocation_secret: FieldLike, claims_hash: FieldLike, credential_type: (bigint | number) }, contract_address: AztecAddressLike, owner: AztecAddressLike, randomness: FieldLike, storage_slot: FieldLike, metadata: { stage: (bigint | number), maybe_note_nonce: FieldLike } }, handle_hash: FieldLike, sponsor_slot: (bigint | number)) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** verify_linked(policy: struct, hinted_root_status: struct, hinted_root_authority: struct, hinted_credential: struct, hinted_status: struct, min_age_proven: integer, nationality_alpha3_packed: field, sponsor_slot: integer) */
    verify_linked: ((policy: { credential_type: (bigint | number), constraints: { claim_id: (bigint | number), op: (bigint | number), value: FieldLike }[] }, hinted_root_status: { note: { root_commitment: FieldLike, revocation_secret: FieldLike }, contract_address: AztecAddressLike, owner: AztecAddressLike, randomness: FieldLike, storage_slot: FieldLike, metadata: { stage: (bigint | number), maybe_note_nonce: FieldLike } }, hinted_root_authority: { note: { root_commitment: FieldLike, claims_hash: FieldLike, authority_expiry_ts: (bigint | number), revocation_secret: FieldLike }, contract_address: AztecAddressLike, owner: AztecAddressLike, randomness: FieldLike, storage_slot: FieldLike, metadata: { stage: (bigint | number), maybe_note_nonce: FieldLike } }, hinted_credential: { note: { root_commitment: FieldLike, claims_hash: FieldLike, credential_type: (bigint | number), expiry_ts: (bigint | number) }, contract_address: AztecAddressLike, owner: AztecAddressLike, randomness: FieldLike, storage_slot: FieldLike, metadata: { stage: (bigint | number), maybe_note_nonce: FieldLike } }, hinted_status: { note: { root_commitment: FieldLike, revocation_secret: FieldLike, claims_hash: FieldLike, credential_type: (bigint | number) }, contract_address: AztecAddressLike, owner: AztecAddressLike, randomness: FieldLike, storage_slot: FieldLike, metadata: { stage: (bigint | number), maybe_note_nonce: FieldLike } }, min_age_proven: (bigint | number), nationality_alpha3_packed: FieldLike, sponsor_slot: (bigint | number)) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** verify_linked_consumer(caller: struct, policy: struct, hinted_root_status: struct, hinted_root_authority: struct, hinted_credential: struct, hinted_status: struct, min_age_proven: integer, nationality_alpha3_packed: field, sponsor_slot: integer) */
    verify_linked_consumer: ((caller: AztecAddressLike, policy: { credential_type: (bigint | number), constraints: { claim_id: (bigint | number), op: (bigint | number), value: FieldLike }[] }, hinted_root_status: { note: { root_commitment: FieldLike, revocation_secret: FieldLike }, contract_address: AztecAddressLike, owner: AztecAddressLike, randomness: FieldLike, storage_slot: FieldLike, metadata: { stage: (bigint | number), maybe_note_nonce: FieldLike } }, hinted_root_authority: { note: { root_commitment: FieldLike, claims_hash: FieldLike, authority_expiry_ts: (bigint | number), revocation_secret: FieldLike }, contract_address: AztecAddressLike, owner: AztecAddressLike, randomness: FieldLike, storage_slot: FieldLike, metadata: { stage: (bigint | number), maybe_note_nonce: FieldLike } }, hinted_credential: { note: { root_commitment: FieldLike, claims_hash: FieldLike, credential_type: (bigint | number), expiry_ts: (bigint | number) }, contract_address: AztecAddressLike, owner: AztecAddressLike, randomness: FieldLike, storage_slot: FieldLike, metadata: { stage: (bigint | number), maybe_note_nonce: FieldLike } }, hinted_status: { note: { root_commitment: FieldLike, revocation_secret: FieldLike, claims_hash: FieldLike, credential_type: (bigint | number) }, contract_address: AztecAddressLike, owner: AztecAddressLike, randomness: FieldLike, storage_slot: FieldLike, metadata: { stage: (bigint | number), maybe_note_nonce: FieldLike } }, min_age_proven: (bigint | number), nationality_alpha3_packed: FieldLike, sponsor_slot: (bigint | number)) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** verify_linked_instagram(policy: struct, hinted_root_status: struct, hinted_root_authority: struct, hinted_credential: struct, hinted_status: struct, handle_hash: field, sponsor_slot: integer) */
    verify_linked_instagram: ((policy: { credential_type: (bigint | number), constraints: { claim_id: (bigint | number), op: (bigint | number), value: FieldLike }[] }, hinted_root_status: { note: { root_commitment: FieldLike, revocation_secret: FieldLike }, contract_address: AztecAddressLike, owner: AztecAddressLike, randomness: FieldLike, storage_slot: FieldLike, metadata: { stage: (bigint | number), maybe_note_nonce: FieldLike } }, hinted_root_authority: { note: { root_commitment: FieldLike, claims_hash: FieldLike, authority_expiry_ts: (bigint | number), revocation_secret: FieldLike }, contract_address: AztecAddressLike, owner: AztecAddressLike, randomness: FieldLike, storage_slot: FieldLike, metadata: { stage: (bigint | number), maybe_note_nonce: FieldLike } }, hinted_credential: { note: { root_commitment: FieldLike, claims_hash: FieldLike, credential_type: (bigint | number), expiry_ts: (bigint | number) }, contract_address: AztecAddressLike, owner: AztecAddressLike, randomness: FieldLike, storage_slot: FieldLike, metadata: { stage: (bigint | number), maybe_note_nonce: FieldLike } }, hinted_status: { note: { root_commitment: FieldLike, revocation_secret: FieldLike, claims_hash: FieldLike, credential_type: (bigint | number) }, contract_address: AztecAddressLike, owner: AztecAddressLike, randomness: FieldLike, storage_slot: FieldLike, metadata: { stage: (bigint | number), maybe_note_nonce: FieldLike } }, handle_hash: FieldLike, sponsor_slot: (bigint | number)) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** verify_linked_sponsored(caller: struct, policy: struct, hinted_root_status: struct, hinted_root_authority: struct, hinted_credential: struct, hinted_status: struct, min_age_proven: integer, nationality_alpha3_packed: field, sponsor_slot: integer) */
    verify_linked_sponsored: ((caller: AztecAddressLike, policy: { credential_type: (bigint | number), constraints: { claim_id: (bigint | number), op: (bigint | number), value: FieldLike }[] }, hinted_root_status: { note: { root_commitment: FieldLike, revocation_secret: FieldLike }, contract_address: AztecAddressLike, owner: AztecAddressLike, randomness: FieldLike, storage_slot: FieldLike, metadata: { stage: (bigint | number), maybe_note_nonce: FieldLike } }, hinted_root_authority: { note: { root_commitment: FieldLike, claims_hash: FieldLike, authority_expiry_ts: (bigint | number), revocation_secret: FieldLike }, contract_address: AztecAddressLike, owner: AztecAddressLike, randomness: FieldLike, storage_slot: FieldLike, metadata: { stage: (bigint | number), maybe_note_nonce: FieldLike } }, hinted_credential: { note: { root_commitment: FieldLike, claims_hash: FieldLike, credential_type: (bigint | number), expiry_ts: (bigint | number) }, contract_address: AztecAddressLike, owner: AztecAddressLike, randomness: FieldLike, storage_slot: FieldLike, metadata: { stage: (bigint | number), maybe_note_nonce: FieldLike } }, hinted_status: { note: { root_commitment: FieldLike, revocation_secret: FieldLike, claims_hash: FieldLike, credential_type: (bigint | number) }, contract_address: AztecAddressLike, owner: AztecAddressLike, randomness: FieldLike, storage_slot: FieldLike, metadata: { stage: (bigint | number), maybe_note_nonce: FieldLike } }, min_age_proven: (bigint | number), nationality_alpha3_packed: FieldLike, sponsor_slot: (bigint | number)) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** verify_linked_sponsored_instagram(caller: struct, policy: struct, hinted_root_status: struct, hinted_root_authority: struct, hinted_credential: struct, hinted_status: struct, handle_hash: field, sponsor_slot: integer) */
    verify_linked_sponsored_instagram: ((caller: AztecAddressLike, policy: { credential_type: (bigint | number), constraints: { claim_id: (bigint | number), op: (bigint | number), value: FieldLike }[] }, hinted_root_status: { note: { root_commitment: FieldLike, revocation_secret: FieldLike }, contract_address: AztecAddressLike, owner: AztecAddressLike, randomness: FieldLike, storage_slot: FieldLike, metadata: { stage: (bigint | number), maybe_note_nonce: FieldLike } }, hinted_root_authority: { note: { root_commitment: FieldLike, claims_hash: FieldLike, authority_expiry_ts: (bigint | number), revocation_secret: FieldLike }, contract_address: AztecAddressLike, owner: AztecAddressLike, randomness: FieldLike, storage_slot: FieldLike, metadata: { stage: (bigint | number), maybe_note_nonce: FieldLike } }, hinted_credential: { note: { root_commitment: FieldLike, claims_hash: FieldLike, credential_type: (bigint | number), expiry_ts: (bigint | number) }, contract_address: AztecAddressLike, owner: AztecAddressLike, randomness: FieldLike, storage_slot: FieldLike, metadata: { stage: (bigint | number), maybe_note_nonce: FieldLike } }, hinted_status: { note: { root_commitment: FieldLike, revocation_secret: FieldLike, claims_hash: FieldLike, credential_type: (bigint | number) }, contract_address: AztecAddressLike, owner: AztecAddressLike, randomness: FieldLike, storage_slot: FieldLike, metadata: { stage: (bigint | number), maybe_note_nonce: FieldLike } }, handle_hash: FieldLike, sponsor_slot: (bigint | number)) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** verify_sponsored(caller: struct, policy: struct, hinted_credential: struct, hinted_status: struct, min_age_proven: integer, nationality_alpha3_packed: field, sponsor_slot: integer) */
    verify_sponsored: ((caller: AztecAddressLike, policy: { credential_type: (bigint | number), constraints: { claim_id: (bigint | number), op: (bigint | number), value: FieldLike }[] }, hinted_credential: { note: { claims_hash: FieldLike, credential_type: (bigint | number), expiry_ts: (bigint | number) }, contract_address: AztecAddressLike, owner: AztecAddressLike, randomness: FieldLike, storage_slot: FieldLike, metadata: { stage: (bigint | number), maybe_note_nonce: FieldLike } }, hinted_status: { note: { revocation_secret: FieldLike, claims_hash: FieldLike, credential_type: (bigint | number) }, contract_address: AztecAddressLike, owner: AztecAddressLike, randomness: FieldLike, storage_slot: FieldLike, metadata: { stage: (bigint | number), maybe_note_nonce: FieldLike } }, min_age_proven: (bigint | number), nationality_alpha3_packed: FieldLike, sponsor_slot: (bigint | number)) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** verify_sponsored_instagram(caller: struct, policy: struct, hinted_credential: struct, hinted_status: struct, handle_hash: field, sponsor_slot: integer) */
    verify_sponsored_instagram: ((caller: AztecAddressLike, policy: { credential_type: (bigint | number), constraints: { claim_id: (bigint | number), op: (bigint | number), value: FieldLike }[] }, hinted_credential: { note: { claims_hash: FieldLike, credential_type: (bigint | number), expiry_ts: (bigint | number) }, contract_address: AztecAddressLike, owner: AztecAddressLike, randomness: FieldLike, storage_slot: FieldLike, metadata: { stage: (bigint | number), maybe_note_nonce: FieldLike } }, hinted_status: { note: { revocation_secret: FieldLike, claims_hash: FieldLike, credential_type: (bigint | number) }, contract_address: AztecAddressLike, owner: AztecAddressLike, randomness: FieldLike, storage_slot: FieldLike, metadata: { stage: (bigint | number), maybe_note_nonce: FieldLike } }, handle_hash: FieldLike, sponsor_slot: (bigint | number)) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;
  };

  
}
