
/* Autogenerated file, do not edit! */

/* eslint-disable */
import { AztecAddress, CompleteAddress } from '@aztec/aztec.js/addresses';
import { type AbiType, type AztecAddressLike, type ContractArtifact, EventSelector, decodeFromAbi, type EthAddressLike, type FieldLike, type FunctionSelectorLike, loadContractArtifact, loadContractArtifactForPublic, type NoirCompiledContract, type OptionLike, type U128Like, type WrappedFieldLike } from '@aztec/aztec.js/abi';
import { Contract, ContractBase, ContractFunctionInteraction, type ContractMethod, type ContractStorageLayout, DeployMethod } from '@aztec/aztec.js/contracts';
import { EthAddress } from '@aztec/aztec.js/addresses';
import { Fr, Point } from '@aztec/aztec.js/fields';
import { type PublicKey, PublicKeys } from '@aztec/aztec.js/keys';
import type { Wallet } from '@aztec/aztec.js/wallet';
import MagnaCompanyRightsRegistryContractArtifactJson from '../../../contracts/magna-company-rights-registry/target/magna_company_rights_registry-MagnaCompanyRightsRegistry.json' with { type: 'json' };
export const MagnaCompanyRightsRegistryContractArtifact = loadContractArtifact(MagnaCompanyRightsRegistryContractArtifactJson as NoirCompiledContract);



/**
 * Type-safe interface for contract MagnaCompanyRightsRegistry;
 */
export class MagnaCompanyRightsRegistryContract extends ContractBase {
  
  private constructor(
    address: AztecAddress,
    wallet: Wallet,
  ) {
    super(address, MagnaCompanyRightsRegistryContractArtifact, wallet);
  }
  

  
  /**
   * Creates a contract instance.
   * @param address - The deployed contract's address.
   * @param wallet - The wallet to use when interacting with the contract.
   * @returns A new Contract instance.
   */
  public static at(
    address: AztecAddress,
    wallet: Wallet,
  ): MagnaCompanyRightsRegistryContract {
    return Contract.at(address, MagnaCompanyRightsRegistryContract.artifact, wallet) as MagnaCompanyRightsRegistryContract;
  }

  
  /**
   * Creates a tx to deploy a new instance of this contract.
   * @param instantiation - Optional address-affecting parameters (salt, deployer / universalDeploy, publicKeys).
   *                       Salt defaults to a random value; the deployer is locked lazily from the first send-time `from`.
   */
  public static deploy(wallet: Wallet, portal: EthAddressLike, admin: AztecAddressLike) {
    return new DeployMethod(
      PublicKeys.default(),
      wallet,
      MagnaCompanyRightsRegistryContractArtifact,
      (instance, wallet) => MagnaCompanyRightsRegistryContract.at(instance.address, wallet),
      [portal, admin],
    );
  }

  /**
   * Creates a tx to deploy a new instance of this contract using the specified constructor method.
   */
  public static deployWithOpts<M extends keyof MagnaCompanyRightsRegistryContract['methods']>(
    opts: { method?: M; wallet: Wallet },
    ...args: Parameters<MagnaCompanyRightsRegistryContract['methods'][M]>
  ) {
    return new DeployMethod(
      PublicKeys.default(),
      opts.wallet,
      MagnaCompanyRightsRegistryContractArtifact,
      (instance, wallet) => MagnaCompanyRightsRegistryContract.at(instance.address, wallet),
      args,
      opts.method ?? 'constructor',
    );
  }
  

  
  /**
   * Returns this contract's artifact.
   */
  public static get artifact(): ContractArtifact {
    return MagnaCompanyRightsRegistryContractArtifact;
  }

  /**
   * Returns this contract's artifact with public bytecode.
   */
  public static get artifactForPublic(): ContractArtifact {
    return loadContractArtifactForPublic(MagnaCompanyRightsRegistryContractArtifactJson as NoirCompiledContract);
  }
  

  public static get storage(): ContractStorageLayout<'admin' | 'portal' | 'l2_purchase_adapter' | 'remaining_verifies' | 'consumed_verifies' | 'last_credit_nonce' | 'package_id'> {
      return {
        admin: {
      slot: new Fr(1n),
    },
portal: {
      slot: new Fr(3n),
    },
l2_purchase_adapter: {
      slot: new Fr(5n),
    },
remaining_verifies: {
      slot: new Fr(6n),
    },
consumed_verifies: {
      slot: new Fr(7n),
    },
last_credit_nonce: {
      slot: new Fr(8n),
    },
package_id: {
      slot: new Fr(9n),
    }
      } as ContractStorageLayout<'admin' | 'portal' | 'l2_purchase_adapter' | 'remaining_verifies' | 'consumed_verifies' | 'last_credit_nonce' | 'package_id'>;
    }
    

  /** Type-safe wrappers for the public methods exposed by the contract. */
  public declare methods: {
    
    /** claim_l1_credit(sponsor: struct, rights_amount: integer, package_id: field, credit_nonce: field, secret: field, message_leaf_index: field) */
    claim_l1_credit: ((sponsor: AztecAddressLike, rights_amount: (bigint | number), package_id: FieldLike, credit_nonce: FieldLike, secret: FieldLike, message_leaf_index: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** constructor(portal: struct, admin: struct) */
    constructor: ((portal: EthAddressLike, admin: AztecAddressLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** consume_right(amount: integer) */
    consume_right: ((amount: (bigint | number)) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** credit_from_l2_payment(sponsor: struct, rights_amount: integer, package_id: field, credit_nonce: field) */
    credit_from_l2_payment: ((sponsor: AztecAddressLike, rights_amount: (bigint | number), package_id: FieldLike, credit_nonce: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_admin() */
    get_admin: (() => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_company_rights(sponsor: struct) */
    get_company_rights: ((sponsor: AztecAddressLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_consumed_verifies(sponsor: struct) */
    get_consumed_verifies: ((sponsor: AztecAddressLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_l2_purchase_adapter() */
    get_l2_purchase_adapter: (() => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_last_credit_nonce(sponsor: struct) */
    get_last_credit_nonce: ((sponsor: AztecAddressLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_package_id(sponsor: struct) */
    get_package_id: ((sponsor: AztecAddressLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_portal() */
    get_portal: (() => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_remaining_verifies(sponsor: struct) */
    get_remaining_verifies: ((sponsor: AztecAddressLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** initialize_l2_purchase_adapter(adapter: struct) */
    initialize_l2_purchase_adapter: ((adapter: AztecAddressLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** offchain_receive(messages: struct) */
    offchain_receive: ((messages: { ciphertext: FieldLike[], recipient: AztecAddressLike, tx_hash: OptionLike<FieldLike>, anchor_block_timestamp: (bigint | number) }[]) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** public_dispatch(selector: field) */
    public_dispatch: ((selector: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** sync_state(scope: struct) */
    sync_state: ((scope: AztecAddressLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;
  };

  
}
