
/* Autogenerated file, do not edit! */

/* eslint-disable */
import { AztecAddress, CompleteAddress } from '@aztec/aztec.js/addresses';
import { type AbiType, type AztecAddressLike, type ContractArtifact, EventSelector, decodeFromAbi, type EthAddressLike, type FieldLike, type FunctionSelectorLike, loadContractArtifact, loadContractArtifactForPublic, type NoirCompiledContract, type OptionLike, type U128Like, type WrappedFieldLike } from '@aztec/aztec.js/abi';
import { Contract, ContractBase, ContractFunctionInteraction, type ContractMethod, type ContractStorageLayout, DeployMethod } from '@aztec/aztec.js/contracts';
import { EthAddress } from '@aztec/aztec.js/addresses';
import { Fr, Point } from '@aztec/aztec.js/fields';
import { type PublicKey, PublicKeys } from '@aztec/aztec.js/keys';
import type { Wallet } from '@aztec/aztec.js/wallet';
import MagnaWebAuthnAccountContractArtifactJson from '../../../contracts/magna-webauthn-account/target/magna_webauthn_account-MagnaWebAuthnAccount.json' with { type: 'json' };
export const MagnaWebAuthnAccountContractArtifact = loadContractArtifact(MagnaWebAuthnAccountContractArtifactJson as NoirCompiledContract);



/**
 * Type-safe interface for contract MagnaWebAuthnAccount;
 */
export class MagnaWebAuthnAccountContract extends ContractBase {
  
  private constructor(
    address: AztecAddress,
    wallet: Wallet,
  ) {
    super(address, MagnaWebAuthnAccountContractArtifact, wallet);
  }
  

  
  /**
   * Creates a contract instance.
   * @param address - The deployed contract's address.
   * @param wallet - The wallet to use when interacting with the contract.
   * @returns A new Contract instance.
   */
  public static at(
    address: AztecAddress,
    wallet: Wallet,
  ): MagnaWebAuthnAccountContract {
    return Contract.at(address, MagnaWebAuthnAccountContract.artifact, wallet) as MagnaWebAuthnAccountContract;
  }

  
  /**
   * Creates a tx to deploy a new instance of this contract.
   * @param instantiation - Optional address-affecting parameters (salt, deployer / universalDeploy, publicKeys).
   *                       Salt defaults to a random value; the deployer is locked lazily from the first send-time `from`.
   */
  public static deploy(wallet: Wallet, signing_pub_key_x: (bigint | number)[], signing_pub_key_y: (bigint | number)[], rp_id_hash: (bigint | number)[], origin: (bigint | number)[], origin_len: (bigint | number)) {
    return new DeployMethod(
      PublicKeys.default(),
      wallet,
      MagnaWebAuthnAccountContractArtifact,
      (instance, wallet) => MagnaWebAuthnAccountContract.at(instance.address, wallet),
      [signing_pub_key_x, signing_pub_key_y, rp_id_hash, origin, origin_len],
    );
  }

  /**
   * Creates a tx to deploy a new instance of this contract using the specified constructor method.
   */
  public static deployWithOpts<M extends keyof MagnaWebAuthnAccountContract['methods']>(
    opts: { method?: M; wallet: Wallet },
    ...args: Parameters<MagnaWebAuthnAccountContract['methods'][M]>
  ) {
    return new DeployMethod(
      PublicKeys.default(),
      opts.wallet,
      MagnaWebAuthnAccountContractArtifact,
      (instance, wallet) => MagnaWebAuthnAccountContract.at(instance.address, wallet),
      args,
      opts.method ?? 'constructor',
    );
  }
  

  
  /**
   * Returns this contract's artifact.
   */
  public static get artifact(): ContractArtifact {
    return MagnaWebAuthnAccountContractArtifact;
  }

  /**
   * Returns this contract's artifact with public bytecode.
   */
  public static get artifactForPublic(): ContractArtifact {
    return loadContractArtifactForPublic(MagnaWebAuthnAccountContractArtifactJson as NoirCompiledContract);
  }
  

  public static get storage(): ContractStorageLayout<'signing_public_key'> {
      return {
        signing_public_key: {
      slot: new Fr(1n),
    }
      } as ContractStorageLayout<'signing_public_key'>;
    }
    

  /** Type-safe wrappers for the public methods exposed by the contract. */
  public declare methods: {
    
    /** constructor(signing_pub_key_x: array, signing_pub_key_y: array, rp_id_hash: array, origin: array, origin_len: integer) */
    constructor: ((signing_pub_key_x: (bigint | number)[], signing_pub_key_y: (bigint | number)[], rp_id_hash: (bigint | number)[], origin: (bigint | number)[], origin_len: (bigint | number)) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** entrypoint(app_payload: struct, fee_payment_method: integer, cancellable: boolean) */
    entrypoint: ((app_payload: { function_calls: { args_hash: FieldLike, function_selector: FunctionSelectorLike, target_address: AztecAddressLike, is_public: boolean, hide_msg_sender: boolean, is_static: boolean }[], tx_nonce: FieldLike }, fee_payment_method: (bigint | number), cancellable: boolean) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** offchain_receive(messages: struct) */
    offchain_receive: ((messages: { ciphertext: FieldLike[], recipient: AztecAddressLike, tx_hash: OptionLike<FieldLike>, anchor_block_timestamp: (bigint | number) }[]) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** public_dispatch(selector: field) */
    public_dispatch: ((selector: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** sync_state(scope: struct) */
    sync_state: ((scope: AztecAddressLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** verify_private_authwit(inner_hash: field) */
    verify_private_authwit: ((inner_hash: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;
  };

  
}
