
/* Autogenerated file, do not edit! */

/* eslint-disable */
import { AztecAddress, CompleteAddress } from '@aztec/aztec.js/addresses';
import { type AbiType, type AztecAddressLike, type ContractArtifact, EventSelector, decodeFromAbi, type EthAddressLike, type FieldLike, type FunctionSelectorLike, loadContractArtifact, loadContractArtifactForPublic, type NoirCompiledContract, type OptionLike, type U128Like, type WrappedFieldLike } from '@aztec/aztec.js/abi';
import { Contract, ContractBase, ContractFunctionInteraction, type ContractMethod, type ContractStorageLayout, type DeployInstantiationOptions, DeployMethod } from '@aztec/aztec.js/contracts';
import { EthAddress } from '@aztec/aztec.js/addresses';
import { Fr, Point } from '@aztec/aztec.js/fields';
import { type PublicKey, PublicKeys } from '@aztec/aztec.js/keys';
import type { Wallet } from '@aztec/aztec.js/wallet';
import MagnaVerifyMeterHookContractArtifactJson from '../../../contracts/magna-verify-meter-hook/target/magna_verify_meter_hook-MagnaVerifyMeterHook.json' with { type: 'json' };
export const MagnaVerifyMeterHookContractArtifact = loadContractArtifact(MagnaVerifyMeterHookContractArtifactJson as NoirCompiledContract);



/**
 * Type-safe interface for contract MagnaVerifyMeterHook;
 */
export class MagnaVerifyMeterHookContract extends ContractBase {
  
  private constructor(
    address: AztecAddress,
    wallet: Wallet,
  ) {
    super(address, MagnaVerifyMeterHookContractArtifact, wallet);
  }
  

  
  /**
   * Creates a contract instance.
   * @param address - The deployed contract's address.
   * @param wallet - The wallet to use when interacting with the contract.
   * @returns A new Contract instance.
   */
  public static at(
    address: AztecAddress,
    wallet: Wallet,
  ): MagnaVerifyMeterHookContract {
    return Contract.at(address, MagnaVerifyMeterHookContract.artifact, wallet) as MagnaVerifyMeterHookContract;
  }

  
  /**
   * Creates a tx to deploy a new instance of this contract.
   * @param instantiation - Optional address-affecting parameters (salt, deployer / universalDeploy, publicKeys).
   *                       Salt defaults to a random value; the deployer is locked lazily from the first send-time `from`.
   */
  public static deploy(wallet: Wallet, admin: AztecAddressLike, initial_allowlist_mask: (bigint | number), instantiation?: DeployInstantiationOptions) {
    return DeployMethod.create<MagnaVerifyMeterHookContract>(
      wallet,
      {
        artifact: MagnaVerifyMeterHookContractArtifact,
        postDeployCtor: (instance, wallet) => MagnaVerifyMeterHookContract.at(instance.address, wallet),
        args: [admin, initial_allowlist_mask],
      },
      instantiation,
    );
  }

  /**
   * Creates a tx to deploy a new instance of this contract using the specified constructor method.
   */
  public static deployWithOpts<M extends keyof MagnaVerifyMeterHookContract['methods']>(
    opts: { method?: M; wallet: Wallet; instantiation?: DeployInstantiationOptions },
    ...args: Parameters<MagnaVerifyMeterHookContract['methods'][M]>
  ) {
    return DeployMethod.create<MagnaVerifyMeterHookContract>(
      opts.wallet,
      {
        artifact: MagnaVerifyMeterHookContractArtifact,
        postDeployCtor: (instance, wallet) => MagnaVerifyMeterHookContract.at(instance.address, wallet),
        args,
        constructorNameOrArtifact: opts.method ?? 'constructor',
      },
      opts.instantiation,
    );
  }
  

  
  /**
   * Returns this contract's artifact.
   */
  public static get artifact(): ContractArtifact {
    return MagnaVerifyMeterHookContractArtifact;
  }

  /**
   * Returns this contract's artifact with public bytecode.
   */
  public static get artifactForPublic(): ContractArtifact {
    return loadContractArtifactForPublic(MagnaVerifyMeterHookContractArtifactJson as NoirCompiledContract);
  }
  

  public static get storage(): ContractStorageLayout<'admin' | 'issuer' | 'allowlist_mask' | 'metered_verify_count'> {
      return {
        admin: {
      slot: new Fr(1n),
    },
issuer: {
      slot: new Fr(3n),
    },
allowlist_mask: {
      slot: new Fr(4n),
    },
metered_verify_count: {
      slot: new Fr(8n),
    }
      } as ContractStorageLayout<'admin' | 'issuer' | 'allowlist_mask' | 'metered_verify_count'>;
    }
    

  /** Type-safe wrappers for the public methods exposed by the contract. */
  public declare methods: {
    
    /** constructor(admin: struct, initial_allowlist_mask: integer) */
    constructor: ((admin: AztecAddressLike, initial_allowlist_mask: (bigint | number)) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_allowlist_mask() */
    get_allowlist_mask: (() => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_metered_verify_count() */
    get_metered_verify_count: (() => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** is_credential_type_allowed(credential_type: integer) */
    is_credential_type_allowed: ((credential_type: (bigint | number)) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** meter_verify_or_revert(credential_type: integer) */
    meter_verify_or_revert: ((credential_type: (bigint | number)) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** offchain_receive(messages: struct) */
    offchain_receive: ((messages: { ciphertext: FieldLike[], recipient: AztecAddressLike, tx_hash: OptionLike<FieldLike>, anchor_block_timestamp: (bigint | number) }[]) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** public_dispatch(selector: field) */
    public_dispatch: ((selector: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** schedule_allowlist_mask(new_mask: integer) */
    schedule_allowlist_mask: ((new_mask: (bigint | number)) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** set_issuer(new_issuer: struct) */
    set_issuer: ((new_issuer: AztecAddressLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** sync_state(scope: struct) */
    sync_state: ((scope: AztecAddressLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;
  };

  
}
