
/* Autogenerated file, do not edit! */

/* eslint-disable */
import { AztecAddress, CompleteAddress } from '@aztec/aztec.js/addresses';
import { type AbiType, type AztecAddressLike, type ContractArtifact, EventSelector, decodeFromAbi, type EthAddressLike, type FieldLike, type FunctionSelectorLike, loadContractArtifact, loadContractArtifactForPublic, type NoirCompiledContract, type OptionLike, type U128Like, type WrappedFieldLike } from '@aztec/aztec.js/abi';
import { Contract, ContractBase, ContractFunctionInteraction, type ContractMethod, type ContractStorageLayout, DeployMethod } from '@aztec/aztec.js/contracts';
import { EthAddress } from '@aztec/aztec.js/addresses';
import { Fr, Point } from '@aztec/aztec.js/fields';
import { type PublicKey, PublicKeys } from '@aztec/aztec.js/keys';
import type { Wallet } from '@aztec/aztec.js/wallet';
import MagnaRightsPurchaseL2ContractArtifactJson from '../../../contracts/magna-rights-purchase-l2/target/magna_rights_purchase_l2-MagnaRightsPurchaseL2.json' with { type: 'json' };
export const MagnaRightsPurchaseL2ContractArtifact = loadContractArtifact(MagnaRightsPurchaseL2ContractArtifactJson as NoirCompiledContract);



/**
 * Type-safe interface for contract MagnaRightsPurchaseL2;
 */
export class MagnaRightsPurchaseL2Contract extends ContractBase {
  
  private constructor(
    address: AztecAddress,
    wallet: Wallet,
  ) {
    super(address, MagnaRightsPurchaseL2ContractArtifact, wallet);
  }
  

  
  /**
   * Creates a contract instance.
   * @param address - The deployed contract's address.
   * @param wallet - The wallet to use when interacting with the contract.
   * @returns A new Contract instance.
   */
  public static at(
    address: AztecAddress,
    wallet: Wallet,
  ): MagnaRightsPurchaseL2Contract {
    return Contract.at(address, MagnaRightsPurchaseL2Contract.artifact, wallet) as MagnaRightsPurchaseL2Contract;
  }

  
  /**
   * Creates a tx to deploy a new instance of this contract.
   * @param instantiation - Optional address-affecting parameters (salt, deployer / universalDeploy, publicKeys).
   *                       Salt defaults to a random value; the deployer is locked lazily from the first send-time `from`.
   */
  public static deploy(wallet: Wallet, admin: AztecAddressLike, treasury: AztecAddressLike, payment_token: AztecAddressLike, rights_registry: AztecAddressLike, price_per_verify: (bigint | number)) {
    return new DeployMethod(
      PublicKeys.default(),
      wallet,
      MagnaRightsPurchaseL2ContractArtifact,
      (instance, wallet) => MagnaRightsPurchaseL2Contract.at(instance.address, wallet),
      [admin, treasury, payment_token, rights_registry, price_per_verify],
    );
  }

  /**
   * Creates a tx to deploy a new instance of this contract using the specified constructor method.
   */
  public static deployWithOpts<M extends keyof MagnaRightsPurchaseL2Contract['methods']>(
    opts: { method?: M; wallet: Wallet },
    ...args: Parameters<MagnaRightsPurchaseL2Contract['methods'][M]>
  ) {
    return new DeployMethod(
      PublicKeys.default(),
      opts.wallet,
      MagnaRightsPurchaseL2ContractArtifact,
      (instance, wallet) => MagnaRightsPurchaseL2Contract.at(instance.address, wallet),
      args,
      opts.method ?? 'constructor',
    );
  }
  

  
  /**
   * Returns this contract's artifact.
   */
  public static get artifact(): ContractArtifact {
    return MagnaRightsPurchaseL2ContractArtifact;
  }

  /**
   * Returns this contract's artifact with public bytecode.
   */
  public static get artifactForPublic(): ContractArtifact {
    return loadContractArtifactForPublic(MagnaRightsPurchaseL2ContractArtifactJson as NoirCompiledContract);
  }
  

  public static get storage(): ContractStorageLayout<'admin' | 'treasury' | 'payment_token' | 'rights_registry' | 'price_per_verify' | 'next_purchase_id'> {
      return {
        admin: {
      slot: new Fr(1n),
    },
treasury: {
      slot: new Fr(3n),
    },
payment_token: {
      slot: new Fr(5n),
    },
rights_registry: {
      slot: new Fr(7n),
    },
price_per_verify: {
      slot: new Fr(9n),
    },
next_purchase_id: {
      slot: new Fr(11n),
    }
      } as ContractStorageLayout<'admin' | 'treasury' | 'payment_token' | 'rights_registry' | 'price_per_verify' | 'next_purchase_id'>;
    }
    

  /** Type-safe wrappers for the public methods exposed by the contract. */
  public declare methods: {
    
    /** constructor(admin: struct, treasury: struct, payment_token: struct, rights_registry: struct, price_per_verify: integer) */
    constructor: ((admin: AztecAddressLike, treasury: AztecAddressLike, payment_token: AztecAddressLike, rights_registry: AztecAddressLike, price_per_verify: (bigint | number)) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_admin() */
    get_admin: (() => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_next_purchase_id() */
    get_next_purchase_id: (() => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_payment_token() */
    get_payment_token: (() => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_price_per_verify() */
    get_price_per_verify: (() => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_rights_registry() */
    get_rights_registry: (() => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_treasury() */
    get_treasury: (() => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** offchain_receive(messages: struct) */
    offchain_receive: ((messages: { ciphertext: FieldLike[], recipient: AztecAddressLike, tx_hash: OptionLike<FieldLike>, anchor_block_timestamp: (bigint | number) }[]) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** public_dispatch(selector: field) */
    public_dispatch: ((selector: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** purchase_rights_public(sponsor: struct, rights_amount: integer, package_id: field, authwit_nonce: field) */
    purchase_rights_public: ((sponsor: AztecAddressLike, rights_amount: (bigint | number), package_id: FieldLike, authwit_nonce: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** sync_state(scope: struct) */
    sync_state: ((scope: AztecAddressLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;
  };

  
}
