
/* Autogenerated file, do not edit! */

/* eslint-disable */
import { AztecAddress, CompleteAddress } from '@aztec/aztec.js/addresses';
import { type AbiType, type AztecAddressLike, type ContractArtifact, EventSelector, decodeFromAbi, type EthAddressLike, type FieldLike, type FunctionSelectorLike, loadContractArtifact, loadContractArtifactForPublic, type NoirCompiledContract, type OptionLike, type U128Like, type WrappedFieldLike } from '@aztec/aztec.js/abi';
import { Contract, ContractBase, ContractFunctionInteraction, type ContractMethod, type ContractStorageLayout, DeployMethod } from '@aztec/aztec.js/contracts';
import { EthAddress } from '@aztec/aztec.js/addresses';
import { Fr, Point } from '@aztec/aztec.js/fields';
import { type PublicKey, PublicKeys } from '@aztec/aztec.js/keys';
import type { Wallet } from '@aztec/aztec.js/wallet';
import MagnaConsumerContractArtifactJson from '../../../contracts/magna-consumer/target/magna_consumer-MagnaConsumer.json' with { type: 'json' };
export const MagnaConsumerContractArtifact = loadContractArtifact(MagnaConsumerContractArtifactJson as NoirCompiledContract);



/**
 * Type-safe interface for contract MagnaConsumer;
 */
export class MagnaConsumerContract extends ContractBase {
  
  private constructor(
    address: AztecAddress,
    wallet: Wallet,
  ) {
    super(address, MagnaConsumerContractArtifact, wallet);
  }
  

  
  /**
   * Creates a contract instance.
   * @param address - The deployed contract's address.
   * @param wallet - The wallet to use when interacting with the contract.
   * @returns A new Contract instance.
   */
  public static at(
    address: AztecAddress,
    wallet: Wallet,
  ): MagnaConsumerContract {
    return Contract.at(address, MagnaConsumerContract.artifact, wallet) as MagnaConsumerContract;
  }

  
  /**
   * Creates a tx to deploy a new instance of this contract.
   */
  public static deploy(wallet: Wallet, issuer_address: AztecAddressLike) {
    return new DeployMethod<MagnaConsumerContract>(PublicKeys.default(), wallet, MagnaConsumerContractArtifact, (instance, wallet) => MagnaConsumerContract.at(instance.address, wallet), Array.from(arguments).slice(1));
  }

  /**
   * Creates a tx to deploy a new instance of this contract using the specified public keys hash to derive the address.
   */
  public static deployWithPublicKeys(publicKeys: PublicKeys, wallet: Wallet, issuer_address: AztecAddressLike) {
    return new DeployMethod<MagnaConsumerContract>(publicKeys, wallet, MagnaConsumerContractArtifact, (instance, wallet) => MagnaConsumerContract.at(instance.address, wallet), Array.from(arguments).slice(2));
  }

  /**
   * Creates a tx to deploy a new instance of this contract using the specified constructor method.
   */
  public static deployWithOpts<M extends keyof MagnaConsumerContract['methods']>(
    opts: { publicKeys?: PublicKeys; method?: M; wallet: Wallet },
    ...args: Parameters<MagnaConsumerContract['methods'][M]>
  ) {
    return new DeployMethod<MagnaConsumerContract>(
      opts.publicKeys ?? PublicKeys.default(),
      opts.wallet,
      MagnaConsumerContractArtifact,
      (instance, wallet) => MagnaConsumerContract.at(instance.address, wallet),
      Array.from(arguments).slice(1),
      opts.method ?? 'constructor',
    );
  }
  

  
  /**
   * Returns this contract's artifact.
   */
  public static get artifact(): ContractArtifact {
    return MagnaConsumerContractArtifact;
  }

  /**
   * Returns this contract's artifact with public bytecode.
   */
  public static get artifactForPublic(): ContractArtifact {
    return loadContractArtifactForPublic(MagnaConsumerContractArtifactJson as NoirCompiledContract);
  }
  

  public static get storage(): ContractStorageLayout<'issuer' | 'gated_login_count'> {
      return {
        issuer: {
      slot: new Fr(1n),
    },
gated_login_count: {
      slot: new Fr(3n),
    }
      } as ContractStorageLayout<'issuer' | 'gated_login_count'>;
    }
    

  /** Type-safe wrappers for the public methods exposed by the contract. */
  public declare methods: {
    
    /** constructor(issuer_address: struct) */
    constructor: ((issuer_address: AztecAddressLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_gated_login_count() */
    get_gated_login_count: (() => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_issuer() */
    get_issuer: (() => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** login_with_magna(policy: struct, hinted_credential: struct, hinted_status: struct, min_age_proven: integer, nationality_alpha3_packed: field, sponsor_slot: integer) */
    login_with_magna: ((policy: { credential_type: (bigint | number), constraints: { claim_id: (bigint | number), op: (bigint | number), value: FieldLike }[] }, hinted_credential: { note: { claims_hash: FieldLike, credential_type: (bigint | number), expiry_ts: (bigint | number) }, contract_address: AztecAddressLike, owner: AztecAddressLike, randomness: FieldLike, storage_slot: FieldLike, metadata: { stage: (bigint | number), maybe_note_nonce: FieldLike } }, hinted_status: { note: { revocation_secret: FieldLike, claims_hash: FieldLike, credential_type: (bigint | number) }, contract_address: AztecAddressLike, owner: AztecAddressLike, randomness: FieldLike, storage_slot: FieldLike, metadata: { stage: (bigint | number), maybe_note_nonce: FieldLike } }, min_age_proven: (bigint | number), nationality_alpha3_packed: FieldLike, sponsor_slot: (bigint | number)) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** offchain_receive(messages: struct) */
    offchain_receive: ((messages: { ciphertext: FieldLike[], recipient: AztecAddressLike, tx_hash: OptionLike<FieldLike>, anchor_block_timestamp: (bigint | number) }[]) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** public_dispatch(selector: field) */
    public_dispatch: ((selector: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** sync_state(scope: struct) */
    sync_state: ((scope: AztecAddressLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;
  };

  
}
