
/* Autogenerated file, do not edit! */

/* eslint-disable */
import { AztecAddress, CompleteAddress } from '@aztec/aztec.js/addresses';
import { type AbiType, type AztecAddressLike, type ContractArtifact, EventSelector, decodeFromAbi, type EthAddressLike, type FieldLike, type FunctionSelectorLike, loadContractArtifact, loadContractArtifactForPublic, type NoirCompiledContract, type U128Like, type WrappedFieldLike } from '@aztec/aztec.js/abi';
import { Contract, ContractBase, ContractFunctionInteraction, type ContractMethod, type ContractStorageLayout, DeployMethod } from '@aztec/aztec.js/contracts';
import { EthAddress } from '@aztec/aztec.js/addresses';
import { Fr, Point } from '@aztec/aztec.js/fields';
import { type PublicKey, PublicKeys } from '@aztec/aztec.js/keys';
import type { Wallet } from '@aztec/aztec.js/wallet';
import MagnaCompanySponsorContractArtifactJson from '../../../contracts/magna-company-sponsor/target/magna_company_sponsor-MagnaCompanySponsor.json' with { type: 'json' };
export const MagnaCompanySponsorContractArtifact = loadContractArtifact(MagnaCompanySponsorContractArtifactJson as NoirCompiledContract);



/**
 * Type-safe interface for contract MagnaCompanySponsor;
 */
export class MagnaCompanySponsorContract extends ContractBase {
  
  private constructor(
    address: AztecAddress,
    wallet: Wallet,
  ) {
    super(address, MagnaCompanySponsorContractArtifact, wallet);
  }
  

  
  /**
   * Creates a contract instance.
   * @param address - The deployed contract's address.
   * @param wallet - The wallet to use when interacting with the contract.
   * @returns A new Contract instance.
   */
  public static at(
    address: AztecAddress,
    wallet: Wallet,
  ): MagnaCompanySponsorContract {
    return Contract.at(address, MagnaCompanySponsorContract.artifact, wallet) as MagnaCompanySponsorContract;
  }

  
  /**
   * Creates a tx to deploy a new instance of this contract.
   */
  public static deploy(wallet: Wallet, admin: AztecAddressLike, max_fee_cap: (bigint | number)) {
    return new DeployMethod<MagnaCompanySponsorContract>(PublicKeys.default(), wallet, MagnaCompanySponsorContractArtifact, (instance, wallet) => MagnaCompanySponsorContract.at(instance.address, wallet), Array.from(arguments).slice(1));
  }

  /**
   * Creates a tx to deploy a new instance of this contract using the specified public keys hash to derive the address.
   */
  public static deployWithPublicKeys(publicKeys: PublicKeys, wallet: Wallet, admin: AztecAddressLike, max_fee_cap: (bigint | number)) {
    return new DeployMethod<MagnaCompanySponsorContract>(publicKeys, wallet, MagnaCompanySponsorContractArtifact, (instance, wallet) => MagnaCompanySponsorContract.at(instance.address, wallet), Array.from(arguments).slice(2));
  }

  /**
   * Creates a tx to deploy a new instance of this contract using the specified constructor method.
   */
  public static deployWithOpts<M extends keyof MagnaCompanySponsorContract['methods']>(
    opts: { publicKeys?: PublicKeys; method?: M; wallet: Wallet },
    ...args: Parameters<MagnaCompanySponsorContract['methods'][M]>
  ) {
    return new DeployMethod<MagnaCompanySponsorContract>(
      opts.publicKeys ?? PublicKeys.default(),
      opts.wallet,
      MagnaCompanySponsorContractArtifact,
      (instance, wallet) => MagnaCompanySponsorContract.at(instance.address, wallet),
      Array.from(arguments).slice(1),
      opts.method ?? 'constructor',
    );
  }
  

  
  /**
   * Returns this contract's artifact.
   */
  public static get artifact(): ContractArtifact {
    return MagnaCompanySponsorContractArtifact;
  }

  /**
   * Returns this contract's artifact with public bytecode.
   */
  public static get artifactForPublic(): ContractArtifact {
    return loadContractArtifactForPublic(MagnaCompanySponsorContractArtifactJson as NoirCompiledContract);
  }
  

  public static get storage(): ContractStorageLayout<'admin' | 'issuer' | 'rights_registry' | 'max_fee_cap' | 'sponsored_verify_count'> {
      return {
        admin: {
      slot: new Fr(1n),
    },
issuer: {
      slot: new Fr(3n),
    },
rights_registry: {
      slot: new Fr(5n),
    },
max_fee_cap: {
      slot: new Fr(7n),
    },
sponsored_verify_count: {
      slot: new Fr(9n),
    }
      } as ContractStorageLayout<'admin' | 'issuer' | 'rights_registry' | 'max_fee_cap' | 'sponsored_verify_count'>;
    }
    

  /** Type-safe wrappers for the public methods exposed by the contract. */
  public declare methods: {
    
    /** constructor(admin: struct, max_fee_cap: integer) */
    constructor: ((admin: AztecAddressLike, max_fee_cap: (bigint | number)) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_issuer() */
    get_issuer: (() => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_max_fee_cap() */
    get_max_fee_cap: (() => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_rights_registry() */
    get_rights_registry: (() => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_sponsored_verify_count() */
    get_sponsored_verify_count: (() => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** initialize_issuer(issuer: struct) */
    initialize_issuer: ((issuer: AztecAddressLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** initialize_rights_registry(rights_registry: struct) */
    initialize_rights_registry: ((rights_registry: AztecAddressLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** offchain_receive(messages: struct) */
    offchain_receive: ((messages: { ciphertext: FieldLike[], recipient: AztecAddressLike, tx_hash: { _is_some: boolean, _value: FieldLike }, anchor_block_timestamp: (bigint | number) }[]) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** public_dispatch(selector: field) */
    public_dispatch: ((selector: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** sponsored_verify(policy: struct, hinted_credential: struct, hinted_status: struct, min_age_proven: integer, nationality_alpha3_packed: field, sponsor_slot: integer) */
    sponsored_verify: ((policy: { credential_type: (bigint | number), constraints: { claim_id: (bigint | number), op: (bigint | number), value: FieldLike }[] }, hinted_credential: { note: { claims_hash: FieldLike, credential_type: (bigint | number), expiry_ts: (bigint | number) }, contract_address: AztecAddressLike, owner: AztecAddressLike, randomness: FieldLike, storage_slot: FieldLike, metadata: { stage: (bigint | number), maybe_note_nonce: FieldLike } }, hinted_status: { note: { revocation_secret: FieldLike, claims_hash: FieldLike, credential_type: (bigint | number) }, contract_address: AztecAddressLike, owner: AztecAddressLike, randomness: FieldLike, storage_slot: FieldLike, metadata: { stage: (bigint | number), maybe_note_nonce: FieldLike } }, min_age_proven: (bigint | number), nationality_alpha3_packed: FieldLike, sponsor_slot: (bigint | number)) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** sponsored_verify_instagram(policy: struct, hinted_credential: struct, hinted_status: struct, handle_hash: field, sponsor_slot: integer) */
    sponsored_verify_instagram: ((policy: { credential_type: (bigint | number), constraints: { claim_id: (bigint | number), op: (bigint | number), value: FieldLike }[] }, hinted_credential: { note: { claims_hash: FieldLike, credential_type: (bigint | number), expiry_ts: (bigint | number) }, contract_address: AztecAddressLike, owner: AztecAddressLike, randomness: FieldLike, storage_slot: FieldLike, metadata: { stage: (bigint | number), maybe_note_nonce: FieldLike } }, hinted_status: { note: { revocation_secret: FieldLike, claims_hash: FieldLike, credential_type: (bigint | number) }, contract_address: AztecAddressLike, owner: AztecAddressLike, randomness: FieldLike, storage_slot: FieldLike, metadata: { stage: (bigint | number), maybe_note_nonce: FieldLike } }, handle_hash: FieldLike, sponsor_slot: (bigint | number)) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** sponsored_verify_linked(policy: struct, hinted_root_status: struct, hinted_root_authority: struct, hinted_credential: struct, hinted_status: struct, min_age_proven: integer, nationality_alpha3_packed: field, sponsor_slot: integer) */
    sponsored_verify_linked: ((policy: { credential_type: (bigint | number), constraints: { claim_id: (bigint | number), op: (bigint | number), value: FieldLike }[] }, hinted_root_status: { note: { root_commitment: FieldLike, revocation_secret: FieldLike }, contract_address: AztecAddressLike, owner: AztecAddressLike, randomness: FieldLike, storage_slot: FieldLike, metadata: { stage: (bigint | number), maybe_note_nonce: FieldLike } }, hinted_root_authority: { note: { root_commitment: FieldLike, claims_hash: FieldLike, authority_expiry_ts: (bigint | number), revocation_secret: FieldLike }, contract_address: AztecAddressLike, owner: AztecAddressLike, randomness: FieldLike, storage_slot: FieldLike, metadata: { stage: (bigint | number), maybe_note_nonce: FieldLike } }, hinted_credential: { note: { root_commitment: FieldLike, claims_hash: FieldLike, credential_type: (bigint | number), expiry_ts: (bigint | number) }, contract_address: AztecAddressLike, owner: AztecAddressLike, randomness: FieldLike, storage_slot: FieldLike, metadata: { stage: (bigint | number), maybe_note_nonce: FieldLike } }, hinted_status: { note: { root_commitment: FieldLike, revocation_secret: FieldLike, claims_hash: FieldLike, credential_type: (bigint | number) }, contract_address: AztecAddressLike, owner: AztecAddressLike, randomness: FieldLike, storage_slot: FieldLike, metadata: { stage: (bigint | number), maybe_note_nonce: FieldLike } }, min_age_proven: (bigint | number), nationality_alpha3_packed: FieldLike, sponsor_slot: (bigint | number)) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** sponsored_verify_linked_instagram(policy: struct, hinted_root_status: struct, hinted_root_authority: struct, hinted_credential: struct, hinted_status: struct, handle_hash: field, sponsor_slot: integer) */
    sponsored_verify_linked_instagram: ((policy: { credential_type: (bigint | number), constraints: { claim_id: (bigint | number), op: (bigint | number), value: FieldLike }[] }, hinted_root_status: { note: { root_commitment: FieldLike, revocation_secret: FieldLike }, contract_address: AztecAddressLike, owner: AztecAddressLike, randomness: FieldLike, storage_slot: FieldLike, metadata: { stage: (bigint | number), maybe_note_nonce: FieldLike } }, hinted_root_authority: { note: { root_commitment: FieldLike, claims_hash: FieldLike, authority_expiry_ts: (bigint | number), revocation_secret: FieldLike }, contract_address: AztecAddressLike, owner: AztecAddressLike, randomness: FieldLike, storage_slot: FieldLike, metadata: { stage: (bigint | number), maybe_note_nonce: FieldLike } }, hinted_credential: { note: { root_commitment: FieldLike, claims_hash: FieldLike, credential_type: (bigint | number), expiry_ts: (bigint | number) }, contract_address: AztecAddressLike, owner: AztecAddressLike, randomness: FieldLike, storage_slot: FieldLike, metadata: { stage: (bigint | number), maybe_note_nonce: FieldLike } }, hinted_status: { note: { root_commitment: FieldLike, revocation_secret: FieldLike, claims_hash: FieldLike, credential_type: (bigint | number) }, contract_address: AztecAddressLike, owner: AztecAddressLike, randomness: FieldLike, storage_slot: FieldLike, metadata: { stage: (bigint | number), maybe_note_nonce: FieldLike } }, handle_hash: FieldLike, sponsor_slot: (bigint | number)) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** sync_state(scope: struct) */
    sync_state: ((scope: AztecAddressLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;
  };

  
}
