[package]
name = "magna_webauthn_account"
authors = [""]
compiler_version = ">=0.25.0"
type = "contract"

[dependencies]
aztec = { git = "https://github.com/AztecProtocol/aztec-packages/", tag = "v5.1.0", directory = "noir-projects/aztec-nr/aztec" }
magna_webauthn = { path = "../magna-webauthn" }
sha256 = { tag = "v0.3.0", git = "https://github.com/noir-lang/sha256" }
